### PR TITLE
Improve xargs cross-compatibility

### PR DESCRIPTION
**Pull request by Mte90**
In this way we can avoid problems on cross compatibility of xargs between various distro.

### CODE REVIEW

**Comment by schlessera** [comment]
I think we should try to keep the old xargs notation for the systems that support because it is actually multiple times faster (it uses 8 parallel processes).

Do you know what specifically cause a problem on your system?

**Comment by Mte90** [comment]
I am studying the problem but seems that is not executed well:
```
vagrant@vvv:/srv/www/wp-cli-dev$ echo php-cli-tools wp-cli wp-cli.github.com builds google-sitemap-generator-cli wp-super-cache-cli server-command restful scaffold-package-command doctor-command dist-archive-command profile-command admin-command handbook media-command find-command cron-command import-command db-command config-command spyc export-command package-command search-replace-command shell-command eval-command scaffold-command entity-command extension-command language-command super-admin-command rewrite-command cache-command checksum-command widget-command role-command core-command automated-tests rpm-build embed-command wp-config-transformer deb-build i18n-command wp-cli-tests regenerate-readme wp-cli-bundle | xargs -n1 -P8 -I% php .maintenance/refresh-repository.php %
Usage: php refresh-repository.php <repository-folder>
```

I will check the documentation of xargs

**Comment by Mte90** [comment]
I tested in on Linux and seems that OSx has a different xargs.

In my version other the wrap of the variable to avoid issues on bash I did that the string with all the packages are divide not by space by but a newline that is the default behaviour of xargs on Linux (to check if it is also on osx).

Now works :-)

**Comment by Mte90** [comment]
The output of composer install now:
```vagrant@vvv:/srv/www/wp-cli-dev$ composer install                            
> php .maintenance/clone-all-repositories.php
Fetching wp-cli/php-cli-tools...
Cloning into 'php-cli-tools'...
Fetching wp-cli/wp-cli...
Cloning into 'wp-cli'...
Fetching wp-cli/wp-cli.github.com...
Cloning into 'wp-cli.github.com'...
Fetching wp-cli/builds...
Cloning into 'builds'...
Fetching wp-cli/google-sitemap-generator-cli...
Cloning into 'google-sitemap-generator-cli'...
Fetching wp-cli/wp-super-cache-cli...
Cloning into 'wp-super-cache-cli'...
Fetching wp-cli/server-command...
Cloning into 'server-command'...
Fetching wp-cli/restful...
Cloning into 'restful'...
Fetching wp-cli/scaffold-package-command...
Cloning into 'scaffold-package-command'...
Fetching wp-cli/doctor-command...
Cloning into 'doctor-command'...
Fetching wp-cli/dist-archive-command...
Cloning into 'dist-archive-command'...
Fetching wp-cli/profile-command...
Cloning into 'profile-command'...
Fetching wp-cli/admin-command...
Cloning into 'admin-command'...
Fetching wp-cli/handbook...
Cloning into 'handbook'...
Fetching wp-cli/media-command...
Cloning into 'media-command'...
Fetching wp-cli/find-command...
Cloning into 'find-command'...
Fetching wp-cli/cron-command...
Cloning into 'cron-command'...
Fetching wp-cli/import-command...
Cloning into 'import-command'...
Fetching wp-cli/db-command...
Cloning into 'db-command'...
Fetching wp-cli/config-command...
Cloning into 'config-command'...
Fetching wp-cli/spyc...
Cloning into 'spyc'...
Fetching wp-cli/export-command...
Cloning into 'export-command'...
Fetching wp-cli/package-command...
Cloning into 'package-command'...
Fetching wp-cli/search-replace-command...
Cloning into 'search-replace-command'...
Fetching wp-cli/shell-command...
Cloning into 'shell-command'...
Fetching wp-cli/eval-command...
Cloning into 'eval-command'...
Fetching wp-cli/scaffold-command...
Cloning into 'scaffold-command'...
Fetching wp-cli/entity-command...
Cloning into 'entity-command'...
Fetching wp-cli/extension-command...
Cloning into 'extension-command'...
Fetching wp-cli/language-command...
Cloning into 'language-command'...
Fetching wp-cli/super-admin-command...
Cloning into 'super-admin-command'...
Fetching wp-cli/rewrite-command...
Cloning into 'rewrite-command'...
Fetching wp-cli/cache-command...
Cloning into 'cache-command'...
Fetching wp-cli/checksum-command...
Cloning into 'checksum-command'...
Fetching wp-cli/widget-command...
Cloning into 'widget-command'...
Fetching wp-cli/role-command...
Cloning into 'role-command'...
Fetching wp-cli/core-command...
Cloning into 'core-command'...
Fetching wp-cli/automated-tests...
Cloning into 'automated-tests'...
Fetching wp-cli/rpm-build...
Cloning into 'rpm-build'...
Fetching wp-cli/embed-command...
Cloning into 'embed-command'...
Fetching wp-cli/wp-config-transformer...
Cloning into 'wp-config-transformer'...
Fetching wp-cli/deb-build...
Cloning into 'deb-build'...
Fetching wp-cli/i18n-command...
Cloning into 'i18n-command'...
Fetching wp-cli/wp-cli-tests...
Cloning into 'wp-cli-tests'...
Fetching wp-cli/regenerate-readme...
Cloning into 'regenerate-readme'...
Fetching wp-cli/wp-cli-bundle...
Cloning into 'wp-cli-bundle'...
--- Refreshing repository server-command ---
Switching to latest master branch...
--- Refreshing repository wp-super-cache-cli ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
--- Refreshing repository google-sitemap-generator-cli ---
Switching to latest master branch...
--- Refreshing repository php-cli-tools ---
Switching to latest master branch...
--- Refreshing repository restful ---
Switching to latest master branch...
--- Refreshing repository wp-cli ---
Switching to latest master branch...
--- Refreshing repository wp-cli.github.com ---
Switching to latest master branch...
--- Refreshing repository builds ---
Switching to latest master branch...
error: pathspec 'master' did not match any file(s) known to git
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository scaffold-package-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository doctor-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository dist-archive-command ---
Switching to latest master branch...
--- Refreshing repository profile-command ---
Switching to latest master branch...
Already on 'master'
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository admin-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository handbook ---
Switching to latest master branch...
Already up to date.
--- Refreshing repository media-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository find-command ---
Switching to latest master branch...
--- Refreshing repository cron-command ---
Switching to latest master branch...
Already on 'master'
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository import-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository db-command ---
Switching to latest master branch...
--- Refreshing repository config-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository spyc ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository export-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository package-command ---
Switching to latest master branch...
Already up to date.
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
--- Refreshing repository search-replace-command ---
Switching to latest master branch...
Already up to date.
--- Refreshing repository shell-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Already up to date.
Your branch is up to date with 'origin/master'.
Pulling latest changes...
--- Refreshing repository eval-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository scaffold-command ---
Switching to latest master branch...
--- Refreshing repository entity-command ---
Switching to latest master branch...
Already up to date.
Already on 'master'
--- Refreshing repository extension-command ---
Switching to latest master branch...
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository language-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository super-admin-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository rewrite-command ---
Switching to latest master branch...
--- Refreshing repository cache-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
--- Refreshing repository checksum-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository widget-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository role-command ---
Switching to latest master branch...
--- Refreshing repository core-command ---
Switching to latest master branch...
Already up to date.
Already on 'master'
--- Refreshing repository automated-tests ---
Switching to latest master branch...
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository rpm-build ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository embed-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Pulling latest changes...
--- Refreshing repository wp-config-transformer ---
Switching to latest master branch...
Already up to date.
--- Refreshing repository deb-build ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository i18n-command ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository wp-cli-tests ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
--- Refreshing repository regenerate-readme ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
--- Refreshing repository wp-cli-bundle ---
Switching to latest master branch...
Already on 'master'
Your branch is up to date with 'origin/master'.
Pulling latest changes...
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 100 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.6.0): Loading from cache
  - Installing symfony/finder (v2.8.49): Loading from cache
  - Installing composer/ca-bundle (1.1.4): Loading from cache
  - Installing composer/spdx-licenses (1.5.0): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing composer/xdebug-handler (1.3.2): Loading from cache
  - Installing justinrainbow/json-schema (5.2.8): Loading from cache
  - Installing squizlabs/php_codesniffer (3.4.0): Loading from cache
  - Installing seld/jsonlint (1.7.1): Loading from cache
  - Installing seld/phar-utils (1.0.1): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing symfony/filesystem (v2.8.49): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/debug (v2.8.49): Loading from cache
  - Installing symfony/console (v2.8.49): Loading from cache
  - Installing symfony/process (v2.8.49): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.5.0): Loading from cache
  - Installing composer/composer (1.8.4): Loading from cache
  - Installing php-composter/php-composter (v0.3.3): Loading from cache
  - Installing behat/gherkin (v2.3.5): Loading from cache
  - Installing gettext/languages (2.5.0): Loading from cache
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing phpcompatibility/php-compatibility (9.1.1): Loading from cache
  - Installing phpcompatibility/phpcompatibility-paragonie (1.0.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing phpdocumentor/reflection-docblock (2.0.5): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing symfony/config (v2.8.49): Loading from cache
  - Installing symfony/dependency-injection (v2.8.49): Loading from cache
  - Installing symfony/event-dispatcher (v2.8.49): Loading from cache
  - Installing symfony/translation (v2.8.49): Loading from cache
  - Installing symfony/yaml (v2.8.49): Loading from cache
  - Installing wp-cli/php-cli-tools (dev-master): Symlinking from php-cli-tools
  - Installing wp-cli/mustangostang-spyc (dev-master): Symlinking from spyc
  - Installing rmccue/requests (v1.7.0): Loading from cache
  - Installing ramsey/array_column (1.1.3): Loading from cache
  - Installing mustache/mustache (v2.12.0): Loading from cache
  - Installing wp-cli/wp-cli (dev-master): Symlinking from wp-cli
  - Installing wp-cli/admin-command (dev-master): Symlinking from admin-command
  - Installing wp-coding-standards/wpcs (1.2.1): Loading from cache
  - Installing wp-cli/eval-command (dev-master): Symlinking from eval-command
  - Installing wp-cli/core-command (dev-master): Symlinking from core-command
  - Installing wp-cli/wp-config-transformer (dev-master): Symlinking from wp-config-transformer
  - Installing wp-cli/config-command (dev-master): Symlinking from config-command
  - Installing roave/security-advisories (dev-master 344bf4e)
  - Installing phpunit/phpunit (4.8.36): Loading from cache
  - Installing phpcompatibility/phpcompatibility-wp (2.0.0): Loading from cache
  - Installing jakub-onderka/php-parallel-lint (v1.0.0): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing behat/behat (v2.5.5): Loading from cache
  - Installing wp-cli/wp-cli-tests (dev-master): Symlinking from wp-cli-tests
  - Installing wp-cli/widget-command (dev-master): Symlinking from widget-command
  - Installing wp-cli/super-admin-command (dev-master): Symlinking from super-admin-command
  - Installing wp-cli/shell-command (dev-master): Symlinking from shell-command
  - Installing wp-cli/server-command (dev-master): Symlinking from server-command
  - Installing wp-cli/search-replace-command (dev-master): Symlinking from search-replace-command
  - Installing wp-cli/scaffold-command (dev-master): Symlinking from scaffold-command
  - Installing wp-cli/role-command (dev-master): Symlinking from role-command
  - Installing wp-cli/rewrite-command (dev-master): Symlinking from rewrite-command
  - Installing wp-cli/package-command (dev-master): Symlinking from package-command
  - Installing wp-cli/media-command (dev-master): Symlinking from media-command
  - Installing wp-cli/language-command (dev-master): Symlinking from language-command
  - Installing wp-cli/import-command (dev-master): Symlinking from import-command
  - Installing mck89/peast (v1.9.1): Loading from cache
  - Installing gettext/gettext (v4.6.2): Loading from cache
  - Installing wp-cli/i18n-command (dev-master): Symlinking from i18n-command
  - Installing wp-cli/extension-command (dev-master): Symlinking from extension-command
  - Installing nb/oxymel (v0.1.0): Loading from cache
  - Installing wp-cli/export-command (dev-master): Symlinking from export-command
  - Installing wp-cli/entity-command (dev-master): Symlinking from entity-command
  - Installing wp-cli/embed-command (dev-master): Symlinking from embed-command
  - Installing wp-cli/db-command (dev-master): Symlinking from db-command
  - Installing wp-cli/cron-command (dev-master): Symlinking from cron-command
  - Installing wp-cli/checksum-command (dev-master): Symlinking from checksum-command
  - Installing wp-cli/cache-command (dev-master): Symlinking from cache-command
  - Installing wp-cli/wp-cli-bundle (dev-master): Symlinking from wp-cli-bundle
  - Installing wp-cli/automated-tests (dev-master): Symlinking from automated-tests
  - Installing wp-cli/dist-archive-command (dev-master): Symlinking from dist-archive-command
  - Installing wp-cli/doctor-command (dev-master): Symlinking from doctor-command
  - Installing wp-cli/find-command (dev-master): Symlinking from find-command
  - Installing wp-cli/google-sitemap-generator-cli (dev-master): Symlinking from google-sitemap-generator-cli
  - Installing wp-cli/profile-command (dev-master): Symlinking from profile-command
  - Installing wp-cli/scaffold-package-command (dev-master): Symlinking from scaffold-package-command
  - Installing wp-cli/regenerate-readme (dev-master): Symlinking from regenerate-readme
  - Installing wp-cli/restful (dev-master): Symlinking from restful
  - Installing wp-cli/wp-super-cache-cli (dev-master): Symlinking from wp-super-cache-cli
symfony/console suggests installing psr/log-implementation (For using the console logger)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/event-dispatcher suggests installing symfony/http-kernel
symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
behat/behat suggests installing behat/mink-extension (for integration with Mink testing framework)
behat/behat suggests installing behat/symfony2-extension (for integration with Symfony2 web framework)
behat/behat suggests installing behat/yii-extension (for integration with Yii web framework)
gettext/gettext suggests installing illuminate/view (Is necessary if you want to use the Blade extractor)
gettext/gettext suggests installing twig/extensions (Is necessary if you want to use the Twig extractor)
gettext/gettext suggests installing twig/twig (Is necessary if you want to use the Twig extractor)
wp-cli/wp-cli-bundle suggests installing psy/psysh (Enhanced `wp shell` functionality)
Package ramsey/array_column is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility,../../phpcompatibility/phpcompatibility-paragonie,../../wp-coding-standards/wpcs,../../phpcompatibility/phpcompatibility-wp
> php .maintenance/symlink-vendor-folders.php
Symlinking wp-cli/admin-command/vendor folder...
Symlinking wp-cli/automated-tests/vendor folder...
Symlinking wp-cli/cache-command/vendor folder...
Symlinking wp-cli/checksum-command/vendor folder...
Symlinking wp-cli/config-command/vendor folder...
Symlinking wp-cli/core-command/vendor folder...
Symlinking wp-cli/cron-command/vendor folder...
Symlinking wp-cli/db-command/vendor folder...
Symlinking wp-cli/dist-archive-command/vendor folder...
Symlinking wp-cli/doctor-command/vendor folder...
Symlinking wp-cli/embed-command/vendor folder...
Symlinking wp-cli/entity-command/vendor folder...
Symlinking wp-cli/eval-command/vendor folder...
Symlinking wp-cli/export-command/vendor folder...
Symlinking wp-cli/extension-command/vendor folder...
Symlinking wp-cli/find-command/vendor folder...
Symlinking wp-cli/google-sitemap-generator-cli/vendor folder...
Symlinking wp-cli/i18n-command/vendor folder...
Symlinking wp-cli/import-command/vendor folder...
Symlinking wp-cli/language-command/vendor folder...
Symlinking wp-cli/media-command/vendor folder...
Symlinking wp-cli/package-command/vendor folder...
Symlinking wp-cli/php-cli-tools/vendor folder...
Symlinking wp-cli/profile-command/vendor folder...
Symlinking wp-cli/regenerate-readme/vendor folder...
Symlinking wp-cli/restful/vendor folder...
Symlinking wp-cli/rewrite-command/vendor folder...
Symlinking wp-cli/role-command/vendor folder...
Symlinking wp-cli/scaffold-command/vendor folder...
Symlinking wp-cli/scaffold-package-command/vendor folder...
Symlinking wp-cli/search-replace-command/vendor folder...
Symlinking wp-cli/server-command/vendor folder...
Symlinking wp-cli/shell-command/vendor folder...
Symlinking wp-cli/spyc/vendor folder...
Symlinking wp-cli/super-admin-command/vendor folder...
Symlinking wp-cli/widget-command/vendor folder...
Symlinking wp-cli/wp-cli/vendor folder...
Symlinking wp-cli/wp-cli-bundle/vendor folder...
Symlinking wp-cli/wp-cli-tests/vendor folder...
Symlinking wp-cli/wp-config-transformer/vendor folder...
Symlinking wp-cli/wp-super-cache-cli/vendor folder...```

**Pull request merged**
